version: '3'

services:
  makepkg:
    image: imrehg/archlinux-makepkg
    volumes:
      - '.:/home/builder/'
    command: makepkg -fi --noconfirm
  
  printsrcinfo:
    image: imrehg/archlinux-makepkg
    volumes:
      - '.:/home/builder/'
    command: makepkg --printsrcinfo > .SRCINFO


